import {
  POSITION,
  DISPLAY,
  FILL_RULE,
  FONT_STYLE,
  MASK,
  MIX_BLEND_MODE,
  OBJECT_FIT,
  OVERFLOW,
  STROKE_LINE_CAP,
  STROKE_LINE_JOIN,
  TEXT_ALIGN,
  TEXT_VERTICAL_ALIGN,
  VISIBILITY,
} from '../style/define';

export const DEFAULT_STYLE = {
  position: 'static',
  display: 'block',
  left: 'auto',
  top: 'auto',
  right: 'auto',
  bottom: 'auto',
  width: 'auto',
  height: 'auto',
  lineHeight: 'normal',
  fontFamily: 'Arial',
  fontSize: 16,
  fontWeight: 400,
  fontStyle: 'normal',
  letterSpacing: 0,
  paragraphSpacing: 0,
  textAlign: 'left',
  textVerticalAlign: 'top',
  textDecoration: [],
  textShadow: '0px 0px 0px transparent',
  color: [0, 0, 0, 1],
  visibility: 'visible',
  opacity: 1,
  backgroundColor: 'transparent',
  fill: [],
  fillOpacity: [],
  fillEnable: [],
  fillMode: [],
  fillRule: 'nonzero',
  stroke: [],
  strokeEnable: [],
  strokeWidth: [],
  strokePosition: [],
  strokeMode: [],
  strokeDasharray: [],
  strokeLinecap: 'butt',
  strokeLinejoin: 'miter',
  strokeMiterlimit: 4,
  translateX: 0,
  translateY: 0,
  translateZ: 0,
  skewX: 0,
  skewY: 0,
  scaleX: 1,
  scaleY: 1,
  rotateX: 0,
  rotateY: 0,
  rotateZ: 0,
  transformOrigin: ['center', 'center'],
  perspective: 0,
  perspectiveOrigin: ['center', 'center'],
  perspectiveSelf: 0,
  mixBlendMode: 'normal',
  pointerEvents: true,
  maskMode: 'none',
  breakMask: false,
  objectFit: 'fill',
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0,
  overflow: 'visible',
  filter: [],
};

export const DEFAULT_COMPUTED_STYLE = {
  position: POSITION.ABSOLUTE,
  display: DISPLAY.BLOCK,
  left: 0,
  top: 0,
  right: 0,
  bottom: 0,
  width: 0,
  height: 0,
  lineHeight: 0,
  fontFamily: 'Arial',
  fontSize: 16,
  fontWeight: 400,
  fontStyle: FONT_STYLE.NORMAL,
  letterSpacing: 0,
  paragraphSpacing: 0,
  textAlign: TEXT_ALIGN.LEFT,
  textVerticalAlign: TEXT_VERTICAL_ALIGN.TOP,
  textDecoration: [],
  textShadow: {
    x: 0,
    y: 0,
    blur: 0,
    color: [0, 0, 0, 0],
  },
  color: [0, 0, 0, 1],
  visibility: VISIBILITY.VISIBLE,
  opacity: 1,
  backgroundColor: [0, 0, 0, 0],
  fill: [],
  fillOpacity: [],
  fillEnable: [],
  fillMode: [],
  fillRule: FILL_RULE.NON_ZERO,
  stroke: [],
  strokeEnable: [],
  strokeWidth: [],
  strokePosition: [],
  strokeMode: [],
  strokeDasharray: [],
  strokeLinecap: STROKE_LINE_CAP.BUTT,
  strokeLinejoin: STROKE_LINE_JOIN.MITER,
  strokeMiterlimit: 4,
  translateX: 0,
  translateY: 0,
  translateZ: 0,
  skewX: 0,
  skewY: 0,
  scaleX: 1,
  scaleY: 1,
  rotateX: 0,
  rotateY: 0,
  rotateZ: 0,
  transformOrigin: [0, 0],
  perspective: 0,
  perspectiveOrigin: [0, 0],
  perspectiveSelf: 0,
  mixBlendMode: MIX_BLEND_MODE.NORMAL,
  pointerEvents: true,
  maskMode: MASK.NONE,
  breakMask: false,
  objectFit: OBJECT_FIT.FILL,
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0,
  overflow: OVERFLOW.VISIBLE,
  filter: [],
};
