export const DEFAULT_STYLE = {
  left: 'auto',
  top: 'auto',
  right: 'auto',
  bottom: 'auto',
  width: 'auto',
  height: 'auto',
  lineHeight: 'normal',
  fontFamily: 'Arial',
  fontSize: 16,
  fontWeight: 400,
  fontStyle: 'normal',
  letterSpacing: 0,
  paragraphSpacing: 0,
  textAlign: 'left',
  textVerticalAlign: 'top',
  textDecoration: [],
  textShadow: '0px 0px 0px transparent',
  color: [0, 0, 0, 1],
  visibility: 'visible',
  opacity: 1,
  backgroundColor: 'transparent',
  fill: [],
  fillOpacity: [],
  fillEnable: [],
  fillMode: [],
  fillRule: 'nonzero',
  stroke: [],
  strokeEnable: [],
  strokeWidth: [],
  strokePosition: [],
  strokeMode: [],
  strokeDasharray: [],
  strokeLinecap: 'butt',
  strokeLinejoin: 'miter',
  strokeMiterlimit: 4,
  translateX: 0,
  translateY: 0,
  translateZ: 0,
  skewX: 0,
  skewY: 0,
  scaleX: 1,
  scaleY: 1,
  rotateX: 0,
  rotateY: 0,
  rotateZ: 0,
  transformOrigin: ['center', 'center'],
  perspective: 0,
  perspectiveOrigin: ['center', 'center'],
  perspectiveSelf: 0,
  mixBlendMode: 'normal',
  pointerEvents: true,
  maskMode: 'none',
  breakMask: false,
  objectFit: 'fill',
  borderTopLeftRadius: 0,
  borderTopRightRadius: 0,
  borderBottomLeftRadius: 0,
  borderBottomRightRadius: 0,
  overflow: 'visible',
  filter: [],
};
